### ISSUE TITLE
can't authenticate with google music

### ISSUE THREAD

**Issue by megamegax** [ewnd9/badtaste#14]
Could you please add a tutorial in the wiki for this? I wanted to connect badtaste to the Google Music, I entered my e-mail address and then i always get the message: "google password (use google's one time passwords generator https://security.google.com/settings/security/apppasswords?pli=1"

I tried to enter the url in my browser, but nothing happened.  What to do here?

**Comment by ewnd9** [comment]
> I tried to enter the url in my browser, but nothing happened

Blank window or 404?

> then i always get the message: 

Is it a just a message or message with input prompt? It should have input prompt where you need to paste your password 

Also checkout https://github.com/jamon/playmusic#authentication, which used underhood for google music access, for auth tips

**Comment by megamegax** [comment]
Well if I enter a character I get the message from above again and again in a new row.

And in the browser I get the message: "The setting you are looking for is not available in your account"

**Comment by ewnd9** [comment]
> And in the browser I get the message: "The setting you are looking for is not available in your account"

I havent seen such problem, you could try to google it

> Well if I enter a character I get the message from above again and again in a new row.

I saw that before, but I had a pasted password, not a manually typed. Paste password, press enter, there will be many repeated messages in a row (possibly length of your password), but it works

As a fast workaround you can create file `~/.badtaste-npm` with content 

```
{
    "googleEmail": "<your-email>",
    "googlePassword": "<your-password>"
}
```

**Comment by megamegax** [comment]
looks like "app password not available for your account" maybe I need Two step verification?

**Comment by ewnd9** [comment]
Sounds good

**Comment by megamegax** [comment]
could it work without that? Because now my credentials are added but none of my musics are showed in the app

**Comment by ewnd9** [comment]
Did you try following https://github.com/jamon/playmusic#authentication? And, please, look at log file (`~/.badtaste-npm-info.log`), it should contains exact exceptions which help determine next steps

**Comment by megamegax** [comment]
Error: 403 error from server
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:72:23)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
Error: 403 error from server
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/badtaste/node_modules/playmusic/play.js:72:23)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)

**Comment by ewnd9** [comment]
403 means bad credentials. Did you enable two-step verification or did you use a plain password?

**Comment by megamegax** [comment]
I am using plain password

ewnd9 notifications@github.com ezt írta (időpont: 2015. nov. 17., K,
22:08):

**Comment by ewnd9** [comment]
Can you confirm this statement for yourself "It also requires a mobile device registered against that account. Ensure you have signed into the app on a phone and that you have played any amount of music" from https://github.com/jamon/playmusic#authentication?

**Comment by megamegax** [comment]
yes,  i used several times the original Google Music app on phone.  I even
had All access for a while.

ewnd9 notifications@github.com ezt írta (időpont: 2015. nov. 18., Sze
1:51):

**Comment by ewnd9** [comment]
I've made little gist to debug `playmusic` logic, please, run it and share output https://gist.github.com/ewnd9/132889c486ffffb6f3c5

**Comment by megamegax** [comment]
{ androidId: '<id>',
  masterToken: '<token>' }
{ kind: 'sj#track',
  id: '8744c39d-ddd5-300b-9230-c5b538210dcb',
  clientId: 'C7KyRMIESPjSTtbjnaH5YQ',
  creationTimestamp: '1447767588228053',
  lastModifiedTimestamp: '1447838484816396',
  recentTimestamp: '1447838484800000',
  deleted: false,
  title: 'Does Your Chewing Gum Lose It\'s Flavor On The Bed Post
Overnight',
  artist: 'The Irish Rovers',
  composer: '',
  album: '36 All-Time Greatest Hits (Disc 2)',
  albumArtist: 'The Irish Rovers',
  year: 0,
  comment: '',
  trackNumber: 8,
  genre: 'Folk',
  durationMillis: '128804',
  beatsPerMinute: 0,
  artistArtRef: [ { url: '
http://lh3.googleusercontent.com/goLUsoD0zLn0VNeDD3w1e5ZRo5_lpJ5aIdYKxpC36nS_jwoyHafjpEI8RCUXq9YKMng7FIQZWoA'
} ],
  playCount: 1,
  totalTrackCount: 0,
  discNumber: 0,
  totalDiscCount: 0,
  rating: '0',
  estimatedSize: '1554638',
  albumId: 'Bpoebcsxfd6iknk46i7zeqtoafq',
  artistId: [ 'Adqnnzbjusxpau5akg2gczk3zee' ],
  nid: 'Tyhg67p7r7xrd6ukwpfvy4uohxm' }

So it is working with this one. I tried again with badtaste, but nothing
changed. I checked, email address and password are the same....

ewnd9 notifications@github.com ezt írta (időpont: 2015. nov. 18., Sze,
10:19):

**Comment by ewnd9** [comment]
Yep, because I used simpler auth in badtaste, which, in fact, was a mistake. However, I've published `v0.5.0` with new auth, you need to update badtaste (`$ npm install -g badtaste`), then rerun setup dialog (`$ badtaste --setup`) and it should works.

**Comment by megamegax** [comment]
Well ^^ I have got an e-mail from google so the login was successfull but
the album list is still empty and I still can't select any music from
google music.

ewnd9 notifications@github.com ezt írta (időpont: 2015. nov. 18., Sze,
11:09):

**Comment by ewnd9** [comment]
Is search working (`> search`)? Album list (`GM Play album`) is populating from search results.

**Comment by megamegax** [comment]
search is not working. It is ok with vk. I can listen the music from there. From local filesystem it is working too. With google music all list are still empty.

**Comment by megamegax** [comment]
this one is done... it is authenticated now..
